version: 0.2

phases:
  install:
    commands:
      - apt-get update
      - apt-get install -y git unzip
  pre_build:
    commands:
      # Retrieving GitHub token from AWS Secrets Manager
      - GITHUB_TOKEN=$(aws secretsmanager get-secret-value --secret-id $GITHUB_TOKEN_SECRET --query SecretString --output text | jq -r '.Token')
      - git config --global credential.helper '!f() { echo "username=Barazii"; echo "password=$GITHUB_TOKEN"; }; f'
      - git config --global user.email $GITHUB_EMAIL
      - git config --global user.name $GITHUB_USER
  build:
    commands:
      # Cloning target repository from github
      - git clone $REPO_URL repo
      - cd repo
      # Downloading modified files from S3
      - aws s3 cp $S3_PATH changes.zip
      - unzip -o changes.zip
      - rm changes.zip
      # git operations
      - git add .
      - git commit -m "Applied changes using gits" || echo "No changes to commit"
      - git push origin main