version: 0.2

phases:
  install:
    commands:
      - apt-get update
      - apt-get install -y git unzip jq
  pre_build:
    commands:
      # Retrieving GitHub token from AWS Secrets Manager
      - GITHUB_TOKEN=$(aws secretsmanager get-secret-value --secret-id $GITHUB_TOKEN_SECRET --query SecretString --output text | jq -r '.Token')
      - git config --global credential.helper '!f() { echo "username=Barazii"; echo "password=$GITHUB_TOKEN"; }; f'
      - git config --global user.email $GITHUB_EMAIL
      - git config --global user.name $GITHUB_USER
  build:
    commands:
      # Cloning target repository from github
      - git clone $REPO_URL repo
      - cd repo
      # Downloading modified files from S3
      - aws s3 cp $S3_PATH changes.zip
      - unzip -o changes.zip
      - rm changes.zip
      # Apply deletions from any manifest(s) if present (POSIX sh-compatible)
      - |
        for MANIFEST_FILE in .gits-manifest-*.json; do
          [ -e "$MANIFEST_FILE" ] || continue
          echo "Found manifest: $MANIFEST_FILE"
          jq -r '.deleted[]? // empty' "$MANIFEST_FILE" 2>/dev/null | while IFS= read -r path; do
            [ -z "$path" ] && continue
            git rm -q --ignore-unmatch -- "$path" || true
          done
          rm -f "$MANIFEST_FILE"
        done
      # git operations
      - git add .
      - 'MSG="${COMMIT_MESSAGE:-Applied changes using gits}"'
      - git commit -m "$MSG" || echo "No changes to commit"
      - git push origin main