version: 0.2

phases:
  install:
    commands:
      - apt-get update
      - apt-get install -y git unzip jq openssh-client curl
  pre_build:
    commands:
      - |
        case "$REPO_URL" in
          https://*)
            if [ -n "$GITHUB_TOKEN_SECRET" ]; then
              GITHUB_TOKEN=$(aws secretsmanager get-secret-value --secret-id "$GITHUB_TOKEN_SECRET" --query SecretString --output text)
            fi
            git config --global credential.helper '!f() { echo "username=$GITHUB_USERNAME"; echo "password=$GITHUB_TOKEN"; }; f'
            ;;
          *)
            if [ -n "$GITHUB_TOKEN_SECRET" ]; then
              GITHUB_TOKEN=$(aws secretsmanager get-secret-value --secret-id "$GITHUB_TOKEN_SECRET" --query SecretString --output text)
            fi
            # Extract owner/repo from REPO_URL (assuming git@github.com:owner/repo.git)
            REPO_PATH=$(echo $REPO_URL | sed 's/git@github.com://' | sed 's/.git$//')
            OWNER=$(echo $REPO_PATH | cut -d'/' -f1)
            REPO=$(echo $REPO_PATH | cut -d'/' -f2)
            SECRET_NAME="github-deploy-key-${GITHUB_EMAIL}"
            mkdir -p ~/.ssh
            if aws secretsmanager describe-secret --secret-id "$SECRET_NAME" >/dev/null 2>&1; then
              # Secret exists: retrieve and use the stored private key
              PRIVATE_KEY=$(aws secretsmanager get-secret-value --secret-id "$SECRET_NAME" --query SecretString --output text)
              echo "$PRIVATE_KEY" > ~/.ssh/id_rsa
            else
              # Secret doesn't exist: generate new key pair, add to GitHub, and store private key
              ssh-keygen -t rsa -b 4096 -f ~/.ssh/id_rsa -N ""
              PUBLIC_KEY=$(cat ~/.ssh/id_rsa.pub)
              PRIVATE_KEY=$(cat ~/.ssh/id_rsa)
              # Add deploy key via GitHub API (only once per repo)
              curl -f -X POST \
                -H "Authorization: token $GITHUB_TOKEN" \
                -H "Accept: application/vnd.github.v3+json" \
                https://api.github.com/repos/$OWNER/$REPO/keys \
                -d "{\"title\":\"CodeBuild Deploy Key\",\"key\":\"$PUBLIC_KEY\",\"read_only\":false}"
              # Store private key in Secrets Manager
              aws secretsmanager create-secret --name "$SECRET_NAME" --secret-string "$PRIVATE_KEY"
            fi
            chmod 600 ~/.ssh/id_rsa
            # Start SSH agent and add key
            eval "$(ssh-agent -s)"
            ssh-add ~/.ssh/id_rsa
            ssh-keyscan github.com >> ~/.ssh/known_hosts
            ;;
        esac
      - git config --global user.email $GITHUB_EMAIL
      - git config --global user.name $GITHUB_DISPLAY_NAME
  build:
    commands:
      # Cloning target repository from github
      - git clone $REPO_URL repo
      - cd repo
      # Downloading modified files from S3
      - aws s3 cp $S3_PATH changes.zip
      - unzip -o changes.zip
      - rm changes.zip
      # Apply deletions from any manifest(s) if present (POSIX sh-compatible)
      - |
        for MANIFEST_FILE in .gits-manifest-*.json; do
          [ -e "$MANIFEST_FILE" ] || continue
          echo "Found manifest: $MANIFEST_FILE"
          jq -r '.deleted[]? // empty' "$MANIFEST_FILE" 2>/dev/null | while IFS= read -r path; do
            [ -z "$path" ] && continue
            git rm -q --ignore-unmatch -- "$path" || true
          done
          rm -f "$MANIFEST_FILE"
        done
      # git operations
      - git add .
      - 'MSG="${COMMIT_MESSAGE:-Applied changes using gits}"'
      - git commit -m "$MSG" || echo "No changes to commit"
      - git push origin main