AWSTemplateFormatVersion: '2010-09-09'
Description: Secrets Manager secret for GitHub OAuth token.

Parameters:
  ProjectName:
    Type: String
    Default: gits
  GitHubToken:
    Type: String
    NoEcho: true
    Description: GitHub personal access token for private repo access.

Resources:
  GitHubTokenSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub '${ProjectName}-github-token'
      SecretString: !Sub '{"oauthToken": "${GitHubToken}"}'

Outputs:
  GitHubTokenSecretArn:
    Value: !Ref GitHubTokenSecret
    Export:
      Name: !Sub '${ProjectName}-GitHubTokenSecretArn'
