AWSTemplateFormatVersion: '2010-09-09'
Description: VPC with private and public subnets, NAT Gateway, VPC endpoints, and Flow Logs for gits project.

Parameters:
  ProjectName:
    Type: String
    Default: gits
  VpcCidr:
    Type: String
    Default: 10.0.0.0/16
  PublicSubnetCidr:
    Type: String
    Default: 10.0.1.0/24
  PrivateSubnetCidr:
    Type: String
    Default: 10.0.2.0/24
  FlowLogsRetentionDays:
    Type: Number
    Default: 14
    Description: Number of days to retain VPC Flow Logs in CloudWatch
  S3PrefixListId:
    Type: String
    Description: Managed prefix list ID for S3.
    Default: pl-23ad484a
  DynamoDBPrefixListId:
    Type: String
    Description: Managed prefix list ID for DynamoDB.
    Default: pl-abb451c2
  # GitHub IP range parameters - these should be periodically updated from https://api.github.com/meta
  # Core GitHub IP ranges (shared across git, web, api services)
  GitHubCoreRange1:
    Type: String
    Default: 192.30.252.0/22
    Description: GitHub core IP range 1
  GitHubCoreRange2:
    Type: String
    Default: 185.199.108.0/22
    Description: GitHub core IP range 2
  GitHubCoreRange3:
    Type: String
    Default: 140.82.112.0/20
    Description: GitHub core IP range 3
  GitHubCoreRange4:
    Type: String
    Default: 143.55.64.0/20
    Description: GitHub core IP range 4

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCidr
      EnableDnsHostnames: true
      EnableDnsSupport: true
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-vpc'

  # VPC Flow Logs
  FlowLogsLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/vpc/${ProjectName}-flow-logs'
      RetentionInDays: !Ref FlowLogsRetentionDays
      Tags:
        - Key: Project
          Value: !Ref ProjectName

  VpcFlowLog:
    Type: AWS::EC2::FlowLog
    Properties:
      ResourceId: !Ref VPC
      ResourceType: VPC
      TrafficType: ALL
      LogDestinationType: cloud-watch-logs
      LogGroupName: !Ref FlowLogsLogGroup
      DeliverLogsPermissionArn: !ImportValue
        Fn::Sub: '${ProjectName}-VpcFlowLogsRoleArn'
      MaxAggregationInterval: 60
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-vpc-flow-log'
        - Key: Project
          Value: !Ref ProjectName

  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-igw'

  InternetGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway

  PublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: !Ref PublicSubnetCidr
      AvailabilityZone: !Select [0, !GetAZs '']
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-public-subnet'

  PrivateSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: !Ref PrivateSubnetCidr
      AvailabilityZone: !Select [0, !GetAZs '']
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-private-subnet'

  NatGateway:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId: !GetAtt NatEip.AllocationId
      SubnetId: !Ref PublicSubnet
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-nat'

  NatEip:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc

  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-public-rt'

  PublicRoute:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway

  PublicSubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet
      RouteTableId: !Ref PublicRouteTable

  PrivateRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-private-rt'

  PrivateRoute:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref PrivateRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId: !Ref NatGateway

  PrivateSubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PrivateSubnet
      RouteTableId: !Ref PrivateRouteTable

  # VPC Endpoints
  S3GatewayEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      VpcId: !Ref VPC
      ServiceName: !Sub 'com.amazonaws.${AWS::Region}.s3'
      VpcEndpointType: Gateway
      RouteTableIds:
        - !Ref PrivateRouteTable

  DynamoDBGatewayEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      VpcId: !Ref VPC
      ServiceName: !Sub 'com.amazonaws.${AWS::Region}.dynamodb'
      VpcEndpointType: Gateway
      RouteTableIds:
        - !Ref PrivateRouteTable

  SecretsManagerEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      VpcId: !Ref VPC
      ServiceName: !Sub 'com.amazonaws.${AWS::Region}.secretsmanager'
      VpcEndpointType: Interface
      SubnetIds:
        - !Ref PrivateSubnet
      SecurityGroupIds:
        - !Ref VpcEndpointSecurityGroup
      PrivateDnsEnabled: true

  EventBridgeEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      VpcId: !Ref VPC
      ServiceName: !Sub 'com.amazonaws.${AWS::Region}.events'
      VpcEndpointType: Interface
      SubnetIds:
        - !Ref PrivateSubnet
      SecurityGroupIds:
        - !Ref VpcEndpointSecurityGroup
      PrivateDnsEnabled: true

  EcrApiEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      VpcId: !Ref VPC
      ServiceName: !Sub 'com.amazonaws.${AWS::Region}.ecr.api'
      VpcEndpointType: Interface
      SubnetIds:
        - !Ref PrivateSubnet
      SecurityGroupIds:
        - !Ref VpcEndpointSecurityGroup
      PrivateDnsEnabled: true

  EcrDkrEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      VpcId: !Ref VPC
      ServiceName: !Sub 'com.amazonaws.${AWS::Region}.ecr.dkr'
      VpcEndpointType: Interface
      SubnetIds:
        - !Ref PrivateSubnet
      SecurityGroupIds:
        - !Ref VpcEndpointSecurityGroup
      PrivateDnsEnabled: true

  CodeBuildEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      VpcId: !Ref VPC
      ServiceName: !Sub 'com.amazonaws.${AWS::Region}.codebuild'
      VpcEndpointType: Interface
      SubnetIds:
        - !Ref PrivateSubnet
      SecurityGroupIds:
        - !Ref VpcEndpointSecurityGroup
      PrivateDnsEnabled: true

  CloudWatchLogsEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      VpcId: !Ref VPC
      ServiceName: !Sub 'com.amazonaws.${AWS::Region}.logs'
      VpcEndpointType: Interface
      SubnetIds:
        - !Ref PrivateSubnet
      SecurityGroupIds:
        - !Ref VpcEndpointSecurityGroup
      PrivateDnsEnabled: true

  StsInterfaceEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      VpcId: !Ref VPC
      ServiceName: !Sub 'com.amazonaws.${AWS::Region}.sts'
      VpcEndpointType: Interface
      SubnetIds:
        - !Ref PrivateSubnet
      SecurityGroupIds:
        - !Ref VpcEndpointSecurityGroup
      PrivateDnsEnabled: true

  # Security Groups
  CodeBuildLenseLambdaSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for CodeBuildLense Lambda
      VpcId: !Ref VPC
      SecurityGroupEgress:
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: !Ref VpcCidr
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          DestinationPrefixListId: !Ref DynamoDBPrefixListId
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-codebuildlense-lambda-sg'

  DeleteLambdaSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for Delete Lambda
      VpcId: !Ref VPC
      SecurityGroupEgress:
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: !Ref VpcCidr
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          DestinationPrefixListId: !Ref DynamoDBPrefixListId
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-delete-lambda-sg'

  GetStatusLambdaSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for GetStatus Lambda
      VpcId: !Ref VPC
      SecurityGroupEgress:
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: !Ref VpcCidr
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          DestinationPrefixListId: !Ref DynamoDBPrefixListId
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-getstatus-lambda-sg'

  GitsOpsLambdaSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for GitsOps Lambda
      VpcId: !Ref VPC
      SecurityGroupEgress:
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: !Ref VpcCidr
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          DestinationPrefixListId: !Ref S3PrefixListId
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          DestinationPrefixListId: !Ref DynamoDBPrefixListId
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-gitsops-lambda-sg'

  CodeBuildSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for CodeBuild
      VpcId: !Ref VPC
      SecurityGroupEgress:
        # SSH access to GitHub for Git SSH cloning - restricted to GitHub IP ranges
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          DestinationPrefixListId: !Ref GitHubSshPrefixList
          Description: Allow SSH to GitHub for Git cloning
        # HTTPS access to GitHub for API and HTTPS cloning - restricted to GitHub IP ranges
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          DestinationPrefixListId: !Ref GitHubHttpsPrefixList
          Description: Allow HTTPS to GitHub for API and web cloning
        # HTTPS access to VPC endpoints (ECR, CloudWatch Logs, etc.)
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: !Ref VpcCidr
          Description: Allow HTTPS to VPC endpoints within VPC
        # HTTPS access to S3 via gateway endpoint
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          DestinationPrefixListId: !Ref S3PrefixListId
          Description: Allow HTTPS to S3 via gateway endpoint
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-codebuild-sg'
  
  # Security group for VPC Interface Endpoints - allows inbound HTTPS from VPC
  VpcEndpointSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for VPC Interface Endpoints
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: !Ref VpcCidr
          Description: Allow HTTPS from within VPC
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-vpc-endpoint-sg'

  # Custom Prefix Lists for GitHub IP ranges
  # These prefix lists contain GitHub's published IP ranges for enhanced security
  # Periodically update entries from https://api.github.com/meta
  
  # Prefix list for GitHub HTTPS traffic (API, web cloning) - TCP 443
  GitHubHttpsPrefixList:
    Type: AWS::EC2::PrefixList
    Properties:
      PrefixListName: !Sub '${ProjectName}-github-https'
      AddressFamily: IPv4
      MaxEntries: 20
      Entries:
        # Core GitHub ranges (shared across git, web, api services)
        - Cidr: !Ref GitHubCoreRange1
          Description: GitHub core range 1 (192.30.252.0/22)
        - Cidr: !Ref GitHubCoreRange2
          Description: GitHub core range 2 (185.199.108.0/22)
        - Cidr: !Ref GitHubCoreRange3
          Description: GitHub core range 3 (140.82.112.0/20)
        - Cidr: !Ref GitHubCoreRange4
          Description: GitHub core range 4 (143.55.64.0/20)
        # Additional web/api specific ranges - sample of commonly used
        - Cidr: 20.201.28.151/32
          Description: GitHub web/api endpoint
        - Cidr: 20.205.243.166/32
          Description: GitHub web/api endpoint
        - Cidr: 20.87.245.0/32
          Description: GitHub web/api endpoint
        - Cidr: 4.237.22.38/32
          Description: GitHub web/api endpoint
        - Cidr: 20.207.73.82/32
          Description: GitHub web/api endpoint
        - Cidr: 20.175.192.147/32
          Description: GitHub web/api endpoint
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-github-https-prefix-list'
        - Key: Project
          Value: !Ref ProjectName
        - Key: Purpose
          Value: GitHub HTTPS traffic (API and web cloning)

  # Prefix list for GitHub SSH traffic (Git SSH cloning) - TCP 22
  GitHubSshPrefixList:
    Type: AWS::EC2::PrefixList
    Properties:
      PrefixListName: !Sub '${ProjectName}-github-ssh'
      AddressFamily: IPv4
      MaxEntries: 20
      Entries:
        # Core GitHub ranges (shared across git, web, api services)
        - Cidr: !Ref GitHubCoreRange1
          Description: GitHub core range 1 (192.30.252.0/22)
        - Cidr: !Ref GitHubCoreRange2
          Description: GitHub core range 2 (185.199.108.0/22)
        - Cidr: !Ref GitHubCoreRange3
          Description: GitHub core range 3 (140.82.112.0/20)
        - Cidr: !Ref GitHubCoreRange4
          Description: GitHub core range 4 (143.55.64.0/20)
        # Git-specific SSH endpoints
        - Cidr: 20.201.28.152/32
          Description: GitHub git SSH endpoint
        - Cidr: 20.205.243.160/32
          Description: GitHub git SSH endpoint
        - Cidr: 20.87.245.4/32
          Description: GitHub git SSH endpoint
        - Cidr: 4.237.22.40/32
          Description: GitHub git SSH endpoint
        - Cidr: 20.207.73.83/32
          Description: GitHub git SSH endpoint
        - Cidr: 20.175.192.146/32
          Description: GitHub git SSH endpoint
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-github-ssh-prefix-list'
        - Key: Project
          Value: !Ref ProjectName
        - Key: Purpose
          Value: GitHub SSH traffic (Git SSH cloning)

Outputs:
  VpcId:
    Description: VPC ID
    Value: !Ref VPC
    Export:
      Name: !Sub '${ProjectName}-VpcId'

  PrivateSubnetId:
    Description: Private Subnet ID
    Value: !Ref PrivateSubnet
    Export:
      Name: !Sub '${ProjectName}-PrivateSubnetId'

  PublicSubnetId:
    Description: Public Subnet ID
    Value: !Ref PublicSubnet
    Export:
      Name: !Sub '${ProjectName}-PublicSubnetId'

  CodeBuildLenseLambdaSGId:
    Description: CodeBuildLense Lambda Security Group ID
    Value: !Ref CodeBuildLenseLambdaSG
    Export:
      Name: !Sub '${ProjectName}-CodeBuildLenseLambdaSGId'

  DeleteLambdaSGId:
    Description: Delete Lambda Security Group ID
    Value: !Ref DeleteLambdaSG
    Export:
      Name: !Sub '${ProjectName}-DeleteLambdaSGId'

  GetStatusLambdaSGId:
    Description: GetStatus Lambda Security Group ID
    Value: !Ref GetStatusLambdaSG
    Export:
      Name: !Sub '${ProjectName}-GetStatusLambdaSGId'

  GitsOpsLambdaSGId:
    Description: GitsOps Lambda Security Group ID
    Value: !Ref GitsOpsLambdaSG
    Export:
      Name: !Sub '${ProjectName}-GitsOpsLambdaSGId'

  CodeBuildSecurityGroupId:
    Description: CodeBuild Security Group ID
    Value: !Ref CodeBuildSecurityGroup
    Export:
      Name: !Sub '${ProjectName}-CodeBuildSecurityGroupId'

  VpcEndpointSecurityGroupId:
    Description: VPC Endpoint Security Group ID
    Value: !Ref VpcEndpointSecurityGroup
    Export:
      Name: !Sub '${ProjectName}-VpcEndpointSecurityGroupId'

  FlowLogsLogGroupName:
    Description: CloudWatch Log Group for VPC Flow Logs
    Value: !Ref FlowLogsLogGroup
    Export:
      Name: !Sub '${ProjectName}-FlowLogsLogGroupName'

  GitHubHttpsPrefixListId:
    Description: Prefix List ID for GitHub HTTPS traffic
    Value: !Ref GitHubHttpsPrefixList
    Export:
      Name: !Sub '${ProjectName}-GitHubHttpsPrefixListId'

  GitHubSshPrefixListId:
    Description: Prefix List ID for GitHub SSH traffic
    Value: !Ref GitHubSshPrefixList
    Export:
      Name: !Sub '${ProjectName}-GitHubSshPrefixListId'